import type { CatalogKey } from "@repo/contracts";

/** What each job catalog field means; shown to the compiler so it maps user wording onto them. */
export const JOB_FIELD_GUIDE: Record<Exclude<CatalogKey, "custom">, string> = {
  company: "Hiring company name",
  title: "Job title",
  location: "Office location(s) as written by the employer",
  remote: 'Work arrangement: exactly one of "remote", "hybrid", "onsite"',
  salary: 'Pay range as text, e.g. "USD 120,000–160,000 / year"',
  url: "Link to the job posting",
  department: "Team or department",
  employment_type: "Full-time, Part-time, Contract, Internship",
  posted_at: "When the posting was published (ISO date)",
  description: "Short excerpt of the job description",
  match_reason: "Why the posting matches the request (generated by RUVO)",
};

/** Registry company tags the compiler may use for company preferences. */
export const COMPANY_TAG_GUIDE: Record<string, string> = {
  ai_lab: "Builds frontier AI models (OpenAI, Anthropic, Cohere…)",
  ai_infra: "AI infrastructure: inference, training, vector DBs, ML platforms",
  devtools: "Developer tools and platforms",
  data_platform: "Data platforms and analytics",
  open_source: "Open-source-first companies",
  consumer_tech: "Consumer technology products",
  fintech: "Financial technology",
};
